### ISSUE TITLE
presentations do not render correctly on IE

### ISSUE THREAD

**Issue by leodemoura** [leanprover/presentations#4]
@soonhokong All code blocks are rendered incorrectly on IE. The problem affects both presentations prepared using the org mode. Here is a screenshot

![image](https://cloud.githubusercontent.com/assets/2778936/6280518/6c0dd37e-b863-11e4-8b3e-916c43e50b37.png)

I spent a long time trying to understand what is going on, and had no luck. 
I got the following errors in the IE console:

```
x SCRIPT5: Access is denied.
leanprover.github.io, line 1 character 1

x SCRIPT5009: 'hljs' is undefined

20150218_MSR, line 1134 character 131
```

The second error is related to `highlight.js`. It is really weird, the file sets a variable `hljs`.  
BTW, I tried the slides on the same machine I tested the tutorial.

**Comment by leodemoura** [comment]
The slides also look pretty bad on Win 7 + Firefox. The bottom part is missing.

![image](https://cloud.githubusercontent.com/assets/2778936/6281022/8dda7986-b86c-11e4-89a3-070c2c0cced8.png)

**Comment by soonhokong** [comment]
1. After partially fixing the problem via 39eb298b1a9df59809000daaf38c4ebdffa0874f, code blocks are rendered using ace-editor. However, sometimes I have annoying scrollbars here and there. I'll find a solution for that.
   
   ![screenshot](https://cloud.githubusercontent.com/assets/403281/6284599/cfb3f226-b8bf-11e4-93dc-7fb19c20d866.png)
2. The second one is fixed by 0b44e0df7677c4e8e15ce377f50783e556101b6b. This workaround was mentioned in 50d86a1db886074499459c935da41cfffe9ce6ab.

**Comment by leodemoura** [comment]
THANKS!!!!

**Comment by leodemoura** [comment]
:100:
